name: Ecommerce CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CUSTOM_VAR: value

jobs:
  frontend-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      redis:
        image: redis
        options: --entrypoint "redis-server --requirepass password"

    steps:
      - name: use secret
        run: |
          echo "Access Token: ${{ secrets.ACCESS_TOKEN }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Test frontend
        run: cd frontend && npm test

      - name: Build frontend
        run: cd frontend && npm run build

      - name: Cache frontend build
        uses: actions/cache@v2
        with:
          path: frontend/build
          key: ${{ runner.os }}-frontend-${{ hashFiles('**/build') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Build frontend Docker image
        run: docker build -t frontend-image ./frontend

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Test backend
        run: cd backend && npm test

      - name: Build backend
        run: cd backend && npm run build

      - name: Cache backend build
        uses: actions/cache@v2
        with:
          path: backend/build
          key: ${{ runner.os }}-backend-${{ hashFiles('**/build') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Build backend Docker image
        run: docker build -t backend-image ./backend

      - name: Publish Docker images
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push frontend-image
          docker push backend-image
